spring:
  application:
    name: ms-vehiculos
  datasource:
    url: ${DB_URL:jdbc:mysql://database-prueba.c5dmn71lds4t.us-east-1.rds.amazonaws.com:3306/vehiculos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Duoc.2025}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:9004}
